const Router = require('express')
const router = new Router()
const bookController = require('../controllers/bookController')
const checkRole = require('../middleware/checkRoleMiddleware')

router.post('/', checkRole('author'), bookController.create)
router.post('/rate',bookController.rate)
router.delete('/deleterate',bookController.deleteRate)
router.get('/getrate',bookController.getRate)
router.get('/getrating',bookController.getRating)
router.get('/checkrent',bookController.checkRent)
router.post('/rentbook',bookController.makeRent)
router.delete('/deleterent',bookController.deleteRent)
router.put('/approvebook',bookController.approveBook)
router.delete('/deletebook',bookController.delete)
router.get('/bookstoapprove',bookController.getBooksToApprove)
router.post('/authorship',bookController.makeAuthorship)
router.put('/makebookmark',bookController.makeBookmark)
router.get('/getbookmark',bookController.getBookmark)
router.get('/', bookController.getAll)
router.post('/getbyattribute', bookController.getByAttribute)
router.get('/:id', bookController.getOne)

module.exports = router