const Router = require('express')
const router = new Router()
const bookController = require('../controllers/bookController')
const checkRole = require('../middleware/checkRoleMiddleware')
const checkAuthorOrModerMiddleware = require('../middleware/checkAuthorOrModerMiddleware')
const authMiddleware = require('../middleware/authMiddleware')

router.post('/', checkAuthorOrModerMiddleware(), bookController.create)
router.post('/rate', authMiddleware, bookController.rate)
router.delete('/deleterate', authMiddleware, bookController.deleteRate)
router.get('/getrate', authMiddleware, bookController.getRate)
router.get('/getrating', authMiddleware, bookController.getRating)
router.get('/checkrent', authMiddleware, bookController.checkRent)
router.post('/rentbook', authMiddleware, bookController.makeRent)
router.delete('/deleterent', authMiddleware, bookController.deleteRent)
router.put('/approvebook', checkRole('moder'), bookController.approveBook)
router.delete('/deletebook', checkRole('moder'), bookController.delete)
router.get('/bookstoapprove', checkRole('moder'), bookController.getBooksToApprove)
router.post('/authorship', checkAuthorOrModerMiddleware(), bookController.makeAuthorship)
router.put('/makebookmark', authMiddleware, bookController.makeBookmark)
router.get('/getbookmark', authMiddleware, bookController.getBookmark)
router.get('/', bookController.getAll)
router.post('/getbyattribute', bookController.getByAttribute)
router.get('/:id', authMiddleware, bookController.getOne)

module.exports = router